In [7]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect
import json

In [11]:
#engine = create_engine('sqlite:///../data/chiTransportSAVED.db')
engine = create_engine("sqlite:///project2_heroku/data/chiTransport2.sqlite")
print(engine)

Engine(sqlite:///project2_heroku/data/chiTransport2.sqlite)

In [12]:
inspector = inspect(engine)
inspector.get_table_names()

['randomDivvy', 'randomScoot']

In [63]:
scootColumns = inspector.get_columns('randomScoot')
divvyColumns = inspector.get_columns('randomDivvy')
# for col in scootColumns:
#     print(col['name'], col['type'])

In [69]:
divvyColumns
colNames = [d['name'] for d in divvyColumns]
print(colNames)

[{'name': 'trip_id', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'start_time', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'end_time', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'bikeid', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'tripduration', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'from_station_id', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'from_station_name', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'to_station_id', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'to_station_name', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'usertype', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'gender', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'birthyear', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}]
['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration', 'from_station_id', 'from_station_name', 'to_station_id', 'to_station_name', 'usertype', 'gender', 'birthyear']

In [8]:
scootResults = engine.execute("Select * from randomScoot WHERE [Start Census Tract] != '' AND [End Community Area Number] != '' AND [Trip Distance] != '0'").fetchall()

In [56]:
scootJson = []
#Start and End Time rounded to the nearest hour
for result in scootResults:
    r = {}
    r['Trip ID'] = result[0]
    r['Start Time'] = result[1]
    r['Distance'] = result[3]
    r['Duration'] = result[4]
    r['Start Tract'] = result[6]
    r['End Tract'] = result[7]
    r['Start Community #'] = result[8]
    r['End Community #'] = result[9]
    r['Start Community Name'] = result[10]
    r['End Community Name'] = result[11]
    r['Start Lat'] = float(result[12])
    r['Start Long'] = float(result[13])
    r['End Lat'] = float(result[15])
    r['End Long'] = float(result[16])
    scootJson.append(r)

In [8]:
with open("/../data/scoot.json",'w') as f:
    json.dump(scootJson, f, ensure_ascii=False, indent=4)

In [9]:
short = engine.execute("Select * from randomScoot WHERE [Start Census Tract] != '' AND [End Community Area Number] != '' AND [Trip Distance] != '0' LIMIT 10").fetchall()

In [10]:
shortJson = []
for result in short:
    r = {}
    r['Trip ID'] = result[0]
    r['Start Time'] = result[1]
    r['Distance'] = result[3]
    r['Duration'] = result[4]
    r['Start Tract'] = result[6]
    r['End Tract'] = result[7]
    r['Start Community #'] = result[8]
    r['End Community #'] = result[9]
    r['Start Community Name'] = result[10]
    r['End Community Name'] = result[11]
    r['Start Lat'] = float(result[12])
    r['Start Long'] = float(result[13])
    r['End Lat'] = float(result[15])
    r['End Long'] = float(result[16])
    shortJson.append(r)

In [ ]:
divvy_results = engine.execute("Select * from randomDivvy LIMIT 100000").fetchall()

In [17]:
q2scope = ['2019-04','2019-05']

divvyJson = []
for result in divvy_results:
    if result[1][:7] not in q2scope:
        r = {}
        for i, c in enumerate(colNames):
            if i != 3 and i != 6 and i < 8:
                r[c] = result[i]
        divvyJson.append(r)

In [30]:
short_divvy = engine.execute("Select * from randomDivvy LIMIT 10").fetchall()

In [33]:
shortDivvy = []
for result in short_divvy:
    r = {}
    for i, c in enumerate(divvyColumns):
        if i != 3 and i != 6 and i < 8:
            r[c] = result[i]
    shortDivvy.append(r)

In [5]:
import pandas as pd

In [8]:
pd.read_json('short.json')

,Trip ID,Start Time,Distance,Duration,Start Tract,End Tract,Start Community #,End Community #,Start Community Name,End Community Name,Start Lat,Start Long,End Lat,End Long
0,1219adef-c969-36f4-1219-adefc96936f4,08/16/2019 01:00:00 PM,772,794,17031833000,17031281900,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.885288,-87.657242,41.879248,-87.642624
1,12d4b35e-8c82-4a18-b77c-dd5061b17b56,07/22/2019 04:00:00 PM,817,234,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
2,15b69e57-8a22-40b1-a682-42d52fbeddcb,07/14/2019 07:00:00 PM,6538,2153,17031838100,17031838100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.878665,-87.671681,41.878665,-87.671681
3,11fca7b6-346a-8436-11fc-a7b6346a8436,07/25/2019 12:00:00 PM,370,143,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
4,37d991bd-1b00-46f3-b66e-aa33c88456cc,09/20/2019 05:00:00 PM,1048,232,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
5,38bf3c5e-b783-54ce-8f9c-efe18b6c912d,06/19/2019 01:00:00 PM,627,498,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
6,3467e6cc-1660-5a84-b2bc-c752f8ccc1aa,07/31/2019 06:00:00 PM,1174,421,17031833100,17031280100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.885296,-87.642804
7,179972bc-9418-5fca-9182-34324d9aebfb,07/07/2019 03:00:00 PM,48,75,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
8,38a82171-fa8f-5cf3-921c-d8e8b050d3f1,09/12/2019 06:00:00 PM,1262,6,17031833000,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.885288,-87.657242,41.879077,-87.657045
9,30a3f5af-9063-5e9e-b427-346af920447d,08/29/2019 07:00:00 AM,740,237,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045

In [11]:
import json

with open("short.json",'w') as f:
    json.dump(shortJson, f, ensure_ascii=False, indent=4)

In [16]:
divvy_results[0][1][:7] in q2scope

False

In [19]:
import json

with open("/../data/divvy.json",'w') as f:
    json.dump(divvyJson, f, ensure_ascii=False, indent=4)

2

In [10]:
pd.read_json('../data/scoot.json')

,Trip ID,Start Time,Distance,Duration,Start Tract,End Tract,Start Community #,End Community #,Start Community Name,End Community Name,Start Lat,Start Long,End Lat,End Long
0,1219adef-c969-36f4-1219-adefc96936f4,08/16/2019 01:00:00 PM,772,794,17031833000,17031281900,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.885288,-87.657242,41.879248,-87.642624
1,12d4b35e-8c82-4a18-b77c-dd5061b17b56,07/22/2019 04:00:00 PM,817,234,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
2,15b69e57-8a22-40b1-a682-42d52fbeddcb,07/14/2019 07:00:00 PM,6538,2153,17031838100,17031838100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.878665,-87.671681,41.878665,-87.671681
3,11fca7b6-346a-8436-11fc-a7b6346a8436,07/25/2019 12:00:00 PM,370,143,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
4,37d991bd-1b00-46f3-b66e-aa33c88456cc,09/20/2019 05:00:00 PM,1048,232,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259773,d32223f7-ed6f-594c-ad96-92b5eace7207,09/25/2019 07:00:00 PM,80,119,17031242100,17031241600,24,24,WEST TOWN,WEST TOWN,41.899670,-87.669837,41.906710,-87.665328
259774,ee350f69-d233-5ce3-a339-da8c8c2f6d9e,07/03/2019 07:00:00 PM,1110,367,17031242300,17031243300,24,24,WEST TOWN,WEST TOWN,41.899507,-87.679600,41.892478,-87.664739
259775,f4350bf6-f033-416b-9a12-093676bc0413,08/15/2019 06:00:00 PM,566,113,17031241200,17031241400,24,24,WEST TOWN,WEST TOWN,41.906707,-87.684686,41.906023,-87.675310
259776,f644d8ce-a32d-5c1c-ad92-ca01ef86b9f9,08/30/2019 04:00:00 PM,595,301,17031242100,17031241500,24,24,WEST TOWN,WEST TOWN,41.899670,-87.669837,41.908376,-87.670937
259777,fe97d758-f9eb-4314-85c0-058d56019e39,07/06/2019 03:00:00 PM,1239,321,17031243200,17031242100,24,24,WEST TOWN,WEST TOWN,41.892433,-87.669624,41.899670,-87.669837

In [35]:
with open("divvyShort.json",'w') as f:
    json.dump(shortDivvy, f, ensure_ascii=False, indent=4)

In [34]:
#engine = create_engine("sqlite:///../data/chiTransport2.sqlite")

AttributeError: randomScoot

In [9]:
import requests

url = "https://data.cityofchicago.org/resource/2kfw-zvte.json"

data = requests.get(url).json()

In [3]:
from sqlalchemy import create_engine

db_string = "postgres://postgres:kennwort@localhost/chiScoot"
db = create_engine(db_string)

In [5]:
db.execute("select * from scoot limit 100").fetchall()

[('52c6ef26-ab14-51e0-aa48-038fad47b9d0', '09/11/2019 06:00:00 PM', '09/11/2019 06:00:00 PM', 701, 500, 0, '17031831100', '17031831100', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9428558109477'), Decimal('-87.7174955453414'), 'POINT (-87.7174955453414 41.9428558109477)', Decimal('41.9428558109477'), Decimal('-87.7174955453414'), 'POINT (-87.7174955453414 41.9428558109477)'),
 ('9e5c8d39-12c5-4734-899c-d5c470524e9d', '09/28/2019 03:00:00 PM', '09/28/2019 03:00:00 PM', 2733, 445, 152, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('38a23fe3-9c89-42eb-b1cb-dd680a6f9957', '08/23/2019 01:00:00 PM', '08/23/2019 01:00:00 PM', 1367, 387, 10, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('9e7381b7-4151-5602-9a2a-d0d5bc075f0c', '07/01/2019 06:00:00 PM', '07/01/2019 06:00:00 PM', 0, 179, 0, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('11ee4247-bfb6-55e0-11ee-4247bfb655e0', '07/14/2019 02:00:00 PM', '07/14/2019 02:00:00 PM', 2220, 449, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('124bd8a3-f908-7d56-124b-d8a3f9087d56', '09/23/2019 02:00:00 PM', '09/23/2019 02:00:00 PM', 917, 456, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('1225ecc7-441a-6be2-1225-ecc7441a6be2', '08/25/2019 07:00:00 PM', '08/25/2019 08:00:00 PM', 724, 463, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('917bc7a5-8dc8-4fdc-b5a9-6d14373cb454', '09/26/2019 03:00:00 PM', '09/26/2019 04:00:00 PM', 8209, 1886, 10, None, None, '24', '25', 'WEST TOWN', 'AUSTIN', Decimal('41.9012067343156'), Decimal('-87.6763571260391'), 'POINT (-87.6763571260391 41.9012067343156)', Decimal('41.8941012961134'), Decimal('-87.7631118242259'), 'POINT (-87.7631118242259 41.8941012961134)'),
 ('1824f3f0-bdc9-412a-bf72-06604b5a285a', '07/18/2019 07:00:00 PM', '07/18/2019 07:00:00 PM', 13917, 494, 10, '17031210501', '17031210100', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9374012930469'), Decimal('-87.722330133986'), 'POINT (-87.722330133986 41.9374012930469)', Decimal('41.9428681074369'), Decimal('-87.7013309490493'), 'POINT (-87.7013309490493 41.9428681074369)'),
 ('5606d8e6-0163-50af-b3cb-0bb0799a29e5', '09/18/2019 05:00:00 PM', '09/18/2019 05:00:00 PM', 1400, 730, 0, None, None, '16', '21', 'IRVING PARK', 'AVONDALE', Decimal('41.95358181896'), Decimal('-87.7234524820666'), 'POINT (-87.7234524820666 41.95358181896)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('11e7d320-7a98-05ec-11e7-d3207a9805ec', '07/09/2019 05:00:00 PM', '07/09/2019 05:00:00 PM', 1078, 401, 10, '17031210601', '17031831100', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.937635618126'), Decimal('-87.7122139947814'), 'POINT (-87.7122139947814 41.937635618126)', Decimal('41.9428558109477'), Decimal('-87.7174955453414'), 'POINT (-87.7174955453414 41.9428558109477)'),
 ('4f804a89-c079-47de-be2a-ef1542fe57cd', '06/15/2019 06:00:00 PM', '06/15/2019 06:00:00 PM', 2042, 813, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('11e8fc1d-8264-8160-11e8-fc1d82648160', '07/10/2019 02:00:00 PM', '07/10/2019 02:00:00 PM', 2317, 486, 10, '17031221400', '17031210502', '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9208013139285'), Decimal('-87.6945320393234'), 'POINT (-87.6945320393234 41.9208013139285)', Decimal('41.9337846267449'), Decimal('-87.7220524303469'), 'POINT (-87.7220524303469 41.9337846267449)'),
 ('7bdbcf7f-7263-4097-b1e0-e7895065a33a', '09/20/2019 08:00:00 AM', '09/20/2019 08:00:00 AM', 861, 260, 10, '17031210501', '17031210601', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9374012930469'), Decimal('-87.722330133986'), 'POINT (-87.722330133986 41.9374012930469)', Decimal('41.937635618126'), Decimal('-87.7122139947814'), 'POINT (-87.7122139947814 41.937635618126)'),
 ('99013368-ac97-504f-9259-8c87479b7ede', '08/23/2019 08:00:00 PM', '08/23/2019 08:00:00 PM', 761, 5, 1, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('07af24f6-9227-4fd8-82bf-65185982de53', '07/04/2019 12:00:00 PM', '07/04/2019 12:00:00 PM', 2161, 425, 152, None, None, '16', '21', 'IRVING PARK', 'AVONDALE', Decimal('41.95358181896'), Decimal('-87.7234524820666'), 'POINT (-87.7234524820666 41.95358181896)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('32f9c6c9-e91a-4e7a-bab3-f77c37665877', '09/18/2019 01:00:00 PM', '09/18/2019 02:00:00 PM', 1978, 452, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('b74a0f95-ac04-43c1-bbbe-47f10002ca7c', '07/07/2019 01:00:00 PM', '07/07/2019 02:00:00 PM', 37, 2885, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('124a2eca-7643-16fc-124a-2eca764316fc', '09/22/2019 08:00:00 AM', '09/22/2019 08:00:00 AM', 2961, 827, 10, None, None, '15', '21', 'PORTAGE PARK', 'AVONDALE', Decimal('41.9540281621501'), Decimal('-87.7633999111184'), 'POINT (-87.7633999111184 41.9540281621501)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('8812cc3c-3f94-4d07-b2b7-57d6c8d0875c', '09/06/2019 05:00:00 PM', '09/06/2019 05:00:00 PM', 3017, 679, 10, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('f4267fdb-508c-4edf-be87-1e3899af8ca7', '07/30/2019 05:00:00 PM', '07/30/2019 05:00:00 PM', 1079, 344, 152, '17031210502', '17031210502', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9337846267449'), Decimal('-87.7220524303469'), 'POINT (-87.7220524303469 41.9337846267449)', Decimal('41.9337846267449'), Decimal('-87.7220524303469'), 'POINT (-87.7220524303469 41.9337846267449)'),
 ('707fdb17-b080-4f74-b53a-7557079604db', '08/09/2019 07:00:00 PM', '08/09/2019 07:00:00 PM', 2731, 702, 10, '17031220602', '17031210502', '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9293311773652'), Decimal('-87.7119813661754'), 'POINT (-87.71198136617541 41.9293311773652)', Decimal('41.9337846267449'), Decimal('-87.7220524303469'), 'POINT (-87.7220524303469 41.9337846267449)'),
 ('5b5a74fb-6630-4820-b408-a0ea2ada79a1', '09/10/2019 01:00:00 PM', '09/10/2019 02:00:00 PM', 7556, 1428, 152, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('eda038b1-7d8f-56b3-b7bb-5d19de59b732', '09/02/2019 07:00:00 PM', '09/02/2019 07:00:00 PM', 519, 4, 1, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('121c99b9-6c82-4516-121c-99b96c824516', '08/18/2019 06:00:00 PM', '08/18/2019 06:00:00 PM', 1062, 214, 10, '17031220500', '17031210700', '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9283966009'), Decimal('-87.7049110564962'), 'POINT (-87.7049110564962 41.9283966009)', Decimal('41.9357028994456'), Decimal('-87.7038400759589'), 'POINT (-87.7038400759589 41.93570289944561)'),
 ('84c8c63b-4743-4389-bf43-7c34a3eca8c6', '07/13/2019 02:00:00 PM', '07/13/2019 02:00:00 PM', 1627, 447, 10, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('17c8b66e-d0e1-49c6-ba9f-3a28b05b2c21', '06/18/2019 04:00:00 PM', '06/18/2019 04:00:00 PM', 1278, 384, 10, '17031200100', '17031210400', '20', '21', 'HERMOSA', 'AVONDALE', Decimal('41.9350481285613'), Decimal('-87.7376041954734'), 'POINT (-87.7376041954734 41.9350481285613)', Decimal('41.9357581406651'), Decimal('-87.7302981167554'), 'POINT (-87.7302981167554 41.9357581406651)'),
 ('695005e5-f705-4532-b0e2-364fbddaab87', '09/16/2019 03:00:00 PM', '09/16/2019 03:00:00 PM', 1431, 502, 10, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('121c97b5-6395-c220-121c-97b56395c220', '08/18/2019 06:00:00 PM', '08/18/2019 06:00:00 PM', 1062, 391, 10, '17031210601', '17031210601', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.937635618126'), Decimal('-87.7122139947814'), 'POINT (-87.7122139947814 41.937635618126)', Decimal('41.937635618126'), Decimal('-87.7122139947814'), 'POINT (-87.7122139947814 41.937635618126)'),
 ('11df9c8b-a4a4-3306-11df-9c8ba4a43306', '07/03/2019 11:00:00 AM', '07/03/2019 12:00:00 PM', 32, 186, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('120f917b-f8d9-c26e-120f-917bf8d9c26e', '08/08/2019 09:00:00 PM', '08/08/2019 09:00:00 PM', 1593, 353, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('f9a03e02-7a02-4032-a2a9-7f3e773dff5b', '06/22/2019 08:00:00 PM', '06/22/2019 08:00:00 PM', 3573, 940, 10, None, None, '23', '21', 'HUMBOLDT PARK', 'AVONDALE', Decimal('41.9000698450397'), Decimal('-87.7209188101033'), 'POINT (-87.7209188101033 41.9000698450397)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('861982c5-70f5-4d26-8a1a-fa98457b5b96', '08/22/2019 03:00:00 PM', '08/22/2019 04:00:00 PM', 7655, 1762, 10, None, None, '28', '21', 'NEAR WEST SIDE', 'AVONDALE', Decimal('41.8740053848845'), Decimal('-87.6635178867003'), 'POINT (-87.6635178867003 41.8740053848845)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('5399c658-487b-4a6e-bbc4-e8625dad6424', '08/17/2019 05:00:00 PM', '08/17/2019 06:00:00 PM', 1290, 5576, 10, '17031220602', '17031210502', '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9293311773652'), Decimal('-87.7119813661754'), 'POINT (-87.71198136617541 41.9293311773652)', Decimal('41.9337846267449'), Decimal('-87.7220524303469'), 'POINT (-87.7220524303469 41.9337846267449)'),
 ('9d42505b-47fe-4500-aa21-f0d253968378', '08/16/2019 04:00:00 PM', '08/16/2019 04:00:00 PM', 2091, 442, 152, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('893a3ef3-f29f-4b83-b2a2-04b26b3fb735', '07/03/2019 03:00:00 PM', '07/03/2019 03:00:00 PM', 1597, 447, 152, None, None, '20', '21', 'HERMOSA', 'AVONDALE', Decimal('41.9243477570064'), Decimal('-87.7347401601846'), 'POINT (-87.7347401601846 41.9243477570064)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('120378db-2b50-1bfa-1203-78db2b501bfa', '07/30/2019 04:00:00 PM', '07/30/2019 05:00:00 PM', 7660, 1514, 10, None, None, '24', '21', 'WEST TOWN', 'AVONDALE', Decimal('41.9012067343156'), Decimal('-87.6763571260391'), 'POINT (-87.6763571260391 41.9012067343156)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('ea7c24dc-d3f0-4601-910b-c04eb740a0cb', '08/20/2019 06:00:00 PM', '08/20/2019 06:00:00 PM', 1261, 201, 152, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('61dae175-93f1-41cb-bdba-d006cd0bc7d0', '06/27/2019 05:00:00 PM', '06/27/2019 05:00:00 PM', 2246, 906, 10, '17031220602', '17031210100', '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9293311773652'), Decimal('-87.7119813661754'), 'POINT (-87.71198136617541 41.9293311773652)', Decimal('41.9428681074369'), Decimal('-87.7013309490493'), 'POINT (-87.7013309490493 41.9428681074369)'),
 ('121b2e2e-6c9c-4a68-121b-2e2e6c9c4a68', '08/17/2019 04:00:00 PM', '08/17/2019 04:00:00 PM', 1029, 193, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('a2c10a83-8bfe-55a7-b5e3-b41a950f5733', '09/06/2019 09:00:00 PM', '09/06/2019 09:00:00 PM', 0, 414, 0, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('8a60545b-45e3-491c-b383-9e32700cd679', '09/07/2019 05:00:00 PM', '09/07/2019 05:00:00 PM', 838, 224, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('123d8f49-848e-8c52-123d-8f49848e8c52', '09/12/2019 06:00:00 PM', '09/12/2019 06:00:00 PM', 2092, 442, 10, '17031221400', '17031210100', '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9208013139285'), Decimal('-87.6945320393234'), 'POINT (-87.6945320393234 41.9208013139285)', Decimal('41.9428681074369'), Decimal('-87.7013309490493'), 'POINT (-87.7013309490493 41.9428681074369)'),
 ('1e1f0cf2-471f-566d-8fc0-0501fcd53767', '09/16/2019 07:00:00 PM', '09/16/2019 07:00:00 PM', 386, 3, 1, '17031831100', '17031831100', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9428558109477'), Decimal('-87.7174955453414'), 'POINT (-87.7174955453414 41.9428558109477)', Decimal('41.9428558109477'), Decimal('-87.7174955453414'), 'POINT (-87.7174955453414 41.9428558109477)'),
 ('7c0f1ca6-38b9-4dda-bbf3-583c3ba2252d', '07/14/2019 03:00:00 PM', '07/14/2019 04:00:00 PM', 10724, 3613, 10, None, None, '28', '21', 'NEAR WEST SIDE', 'AVONDALE', Decimal('41.8740053848845'), Decimal('-87.6635178867003'), 'POINT (-87.6635178867003 41.8740053848845)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('9d3e9ace-1ec4-40c5-9c28-b1d392fc0369', '08/09/2019 07:00:00 AM', '08/09/2019 07:00:00 AM', 918, 200, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('11d6d5eb-b3f8-71ec-11d6-d5ebb3f871ec', '06/26/2019 08:00:00 PM', '06/26/2019 08:00:00 PM', 0, 63, 10, '17031210100', '17031210100', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9428681074369'), Decimal('-87.7013309490493'), 'POINT (-87.7013309490493 41.9428681074369)', Decimal('41.9428681074369'), Decimal('-87.7013309490493'), 'POINT (-87.7013309490493 41.9428681074369)'),
 ('73f5ad00-b066-54f9-92db-5c2f02aaedfd', '07/20/2019 12:00:00 PM', '07/20/2019 12:00:00 PM', 804, 364, 0, '17031210501', '17031210501', '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.9374012930469'), Decimal('-87.722330133986'), 'POINT (-87.722330133986 41.9374012930469)', Decimal('41.9374012930469'), Decimal('-87.722330133986'), 'POINT (-87.722330133986 41.9374012930469)'),
 ('613e18df-10ab-5d93-95d8-8cc474717fc3', '08/18/2019 06:00:00 PM', '08/18/2019 06:00:00 PM', 1889, 9, 1, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('11e2590f-5491-211a-11e2-590f5491211a', '07/05/2019 01:00:00 PM', '07/05/2019 01:00:00 PM', 772, 408, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('b2f955d8-d463-80d5-de99-ce2086bad296', '08/16/2019 02:00:00 AM', '08/16/2019 02:00:00 AM', 1735, 360, 10, None, None, '22', '21', 'LOGAN SQUARE', 'AVONDALE', Decimal('41.9227598585219'), Decimal('-87.6991559457654'), 'POINT (-87.6991559457654 41.9227598585219)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),
 ('499381d5-ae67-412f-b2d6-92ffb1b68f23', '07/02/2019 12:00:00 PM', '07/02/2019 12:00:00 PM', 3449, 711, 10, None, None, '26', '25', 'WEST GARFIELD PARK', 'AUSTIN', Decimal('41.8785946681995'), Decimal('-87.7302325118985'), 'POINT (-87.7302325118985 41.8785946681995)', Decimal('41.8941012961134'), Decimal('-87.7631118242259'), 'POINT (-87.7631118242259 41.8941012961134)'),
 ('120391fd-8f29-1316-1203-91fd8f291316', '07/30/2019 06:00:00 PM', '07/30/2019 06:00:00 PM', 2140, 548, 10, None, None, '21', '21', 'AVONDALE', 'AVONDALE', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)', Decimal('41.938665887698'), Decimal('-87.7112106378686'), 'POINT (-87.7112106378686 41.938665887698)'),

In [6]:
db.execute("select * from divvy")

In [9]:
inspector = inspect(db)

In [10]:
inspector.get_columns('divvy')

[{'name': 'trip_id',
  'type': VARCHAR(length=255),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'start_time',
  'type': VARCHAR(length=255),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'end_time',
  'type': VARCHAR(length=255),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'duration',
  'type': VARCHAR(length=255),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'from_station',
  'type': INTEGER(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'from_name',
  'type': VARCHAR(length=255),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'to_station',
  'type': INTEGER(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'to_name',
  'type': VARCHAR(length=255),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None}]