In [60]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect
import json

In [61]:
#engine = create_engine('sqlite:///../data/chiTransportSAVED.db')
engine = create_engine('sqlite:///../data/chiTransport2.sqlite')

In [62]:
inspector = inspect(engine)
inspector.get_table_names()

['randomDivvy', 'randomScoot']

In [63]:
scootColumns = inspector.get_columns('randomScoot')
divvyColumns = inspector.get_columns('randomDivvy')
# for col in scootColumns:
#     print(col['name'], col['type'])

In [69]:
divvyColumns
colNames = [d['name'] for d in divvyColumns]
print(colNames)

[{'name': 'trip_id', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'start_time', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'end_time', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'bikeid', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'tripduration', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'from_station_id', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'from_station_name', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'to_station_id', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'to_station_name', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'usertype', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'gender', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'birthyear', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}]
['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration', 'from_station_id', 'from_station_name', 'to_station_id', 'to_station_name', 'usertype', 'gender', 'birthyear']

In [55]:
scootResults = engine.execute("Select * from randomScoot WHERE [Start Census Tract] != '' AND [End Community Area Number] != '' AND [Trip Distance] != '0'").fetchall()

In [56]:
scootJson = []
#Start and End Time rounded to the nearest hour
for result in scootResults:
    r = {}
    r['Trip ID'] = result[0]
    r['Start Time'] = result[1]
    r['Distance'] = result[3]
    r['Duration'] = result[4]
    r['Start Tract'] = result[6]
    r['End Tract'] = result[7]
    r['Start Community #'] = result[8]
    r['End Community #'] = result[9]
    r['Start Community Name'] = result[10]
    r['End Community Name'] = result[11]
    r['Start Lat'] = float(result[12])
    r['Start Long'] = float(result[13])
    r['End Lat'] = float(result[15])
    r['End Long'] = float(result[16])
    scootJson.append(r)

In [8]:
with open("/../data/scoot.json",'w') as f:
    json.dump(scootJson, f, ensure_ascii=False, indent=4)

In [9]:
short = engine.execute("Select * from randomScoot WHERE [Start Census Tract] != '' AND [End Community Area Number] != '' AND [Trip Distance] != '0' LIMIT 10").fetchall()

In [10]:
shortJson = []
for result in short:
    r = {}
    r['Trip ID'] = result[0]
    r['Start Time'] = result[1]
    r['Distance'] = result[3]
    r['Duration'] = result[4]
    r['Start Tract'] = result[6]
    r['End Tract'] = result[7]
    r['Start Community #'] = result[8]
    r['End Community #'] = result[9]
    r['Start Community Name'] = result[10]
    r['End Community Name'] = result[11]
    r['Start Lat'] = float(result[12])
    r['Start Long'] = float(result[13])
    r['End Lat'] = float(result[15])
    r['End Long'] = float(result[16])
    shortJson.append(r)

In [ ]:
divvy_results = engine.execute("Select * from randomDivvy LIMIT 100000").fetchall()

In [17]:
q2scope = ['2019-04','2019-05']

divvyJson = []
for result in divvy_results:
    if result[1][:7] not in q2scope:
        r = {}
        for i, c in enumerate(colNames):
            if i != 3 and i != 6 and i < 8:
                r[c] = result[i]
        divvyJson.append(r)

In [30]:
short_divvy = engine.execute("Select * from randomDivvy LIMIT 10").fetchall()

In [33]:
shortDivvy = []
for result in short_divvy:
    r = {}
    for i, c in enumerate(divvyColumns):
        if i != 3 and i != 6 and i < 8:
            r[c] = result[i]
    shortDivvy.append(r)

In [5]:
import pandas as pd

In [8]:
pd.read_json('short.json')

,Trip ID,Start Time,Distance,Duration,Start Tract,End Tract,Start Community #,End Community #,Start Community Name,End Community Name,Start Lat,Start Long,End Lat,End Long
0,1219adef-c969-36f4-1219-adefc96936f4,08/16/2019 01:00:00 PM,772,794,17031833000,17031281900,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.885288,-87.657242,41.879248,-87.642624
1,12d4b35e-8c82-4a18-b77c-dd5061b17b56,07/22/2019 04:00:00 PM,817,234,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
2,15b69e57-8a22-40b1-a682-42d52fbeddcb,07/14/2019 07:00:00 PM,6538,2153,17031838100,17031838100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.878665,-87.671681,41.878665,-87.671681
3,11fca7b6-346a-8436-11fc-a7b6346a8436,07/25/2019 12:00:00 PM,370,143,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
4,37d991bd-1b00-46f3-b66e-aa33c88456cc,09/20/2019 05:00:00 PM,1048,232,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
5,38bf3c5e-b783-54ce-8f9c-efe18b6c912d,06/19/2019 01:00:00 PM,627,498,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
6,3467e6cc-1660-5a84-b2bc-c752f8ccc1aa,07/31/2019 06:00:00 PM,1174,421,17031833100,17031280100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.885296,-87.642804
7,179972bc-9418-5fca-9182-34324d9aebfb,07/07/2019 03:00:00 PM,48,75,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
8,38a82171-fa8f-5cf3-921c-d8e8b050d3f1,09/12/2019 06:00:00 PM,1262,6,17031833000,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.885288,-87.657242,41.879077,-87.657045
9,30a3f5af-9063-5e9e-b427-346af920447d,08/29/2019 07:00:00 AM,740,237,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045

In [11]:
import json

with open("short.json",'w') as f:
    json.dump(shortJson, f, ensure_ascii=False, indent=4)

In [16]:
divvy_results[0][1][:7] in q2scope

False

In [19]:
import json

with open("/../data/divvy.json",'w') as f:
    json.dump(divvyJson, f, ensure_ascii=False, indent=4)

2

In [10]:
pd.read_json('../data/scoot.json')

,Trip ID,Start Time,Distance,Duration,Start Tract,End Tract,Start Community #,End Community #,Start Community Name,End Community Name,Start Lat,Start Long,End Lat,End Long
0,1219adef-c969-36f4-1219-adefc96936f4,08/16/2019 01:00:00 PM,772,794,17031833000,17031281900,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.885288,-87.657242,41.879248,-87.642624
1,12d4b35e-8c82-4a18-b77c-dd5061b17b56,07/22/2019 04:00:00 PM,817,234,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
2,15b69e57-8a22-40b1-a682-42d52fbeddcb,07/14/2019 07:00:00 PM,6538,2153,17031838100,17031838100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.878665,-87.671681,41.878665,-87.671681
3,11fca7b6-346a-8436-11fc-a7b6346a8436,07/25/2019 12:00:00 PM,370,143,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
4,37d991bd-1b00-46f3-b66e-aa33c88456cc,09/20/2019 05:00:00 PM,1048,232,17031833100,17031833100,28,28,NEAR WEST SIDE,NEAR WEST SIDE,41.879077,-87.657045,41.879077,-87.657045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259773,d32223f7-ed6f-594c-ad96-92b5eace7207,09/25/2019 07:00:00 PM,80,119,17031242100,17031241600,24,24,WEST TOWN,WEST TOWN,41.899670,-87.669837,41.906710,-87.665328
259774,ee350f69-d233-5ce3-a339-da8c8c2f6d9e,07/03/2019 07:00:00 PM,1110,367,17031242300,17031243300,24,24,WEST TOWN,WEST TOWN,41.899507,-87.679600,41.892478,-87.664739
259775,f4350bf6-f033-416b-9a12-093676bc0413,08/15/2019 06:00:00 PM,566,113,17031241200,17031241400,24,24,WEST TOWN,WEST TOWN,41.906707,-87.684686,41.906023,-87.675310
259776,f644d8ce-a32d-5c1c-ad92-ca01ef86b9f9,08/30/2019 04:00:00 PM,595,301,17031242100,17031241500,24,24,WEST TOWN,WEST TOWN,41.899670,-87.669837,41.908376,-87.670937
259777,fe97d758-f9eb-4314-85c0-058d56019e39,07/06/2019 03:00:00 PM,1239,321,17031243200,17031242100,24,24,WEST TOWN,WEST TOWN,41.892433,-87.669624,41.899670,-87.669837

In [35]:
with open("divvyShort.json",'w') as f:
    json.dump(shortDivvy, f, ensure_ascii=False, indent=4)

In [34]:
#engine = create_engine("sqlite:///../data/chiTransport2.sqlite")

AttributeError: randomScoot

In [9]:
import requests

url = "https://data.cityofchicago.org/resource/2kfw-zvte.json"

data = requests.get(url).json()